apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.mtgcollection.name }}-ingress
  namespace: {{ .Values.mtgcollection.nameSpace }}
  annotations:
    {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Values.mtgcollection.nameSpace }}-upload-limit@kubernetescrd"
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.mtgcollection.ingress.host }}
      secretName: {{ .Values.mtgcollection.secrets }}
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.mtgcollection.ingress.host }}
      http:
        paths:
          - path: /
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Values.mtgcollection.name }}-service
                port:
                  number: {{ .Values.mtgcollection.service.port }}
