apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regcred-external-secret
  namespace: magiccollection
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: regcred
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: imagePullSecret
        decodingStrategy: Base64
